pipeline {

    agent any

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/tushar12357/ai-codebase-assistant'
            }
        }

        stage('Build Containers') {
            steps {
                sh 'docker compose -f infra/docker/docker-compose.yml build'
            }
        }

        stage('Run Tests') {
            steps {
                sh 'npm install'
                sh 'npm test'
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker compose -f infra/docker/docker-compose.yml up -d'
            }
        }
    }
}