pipeline {

    agent any

    environment {
        COMPOSE_FILE = "infra/docker/docker-compose.yml"
    }

    stages {

        stage('Checkout') {
            steps {
                git 'https://github.com/tushar12357/ai-codebase-assistant'
            }
        }

        stage('Build Containers') {
            steps {
                sh 'docker compose -f $COMPOSE_FILE build'
            }
        }

        stage('Start Services') {
            steps {
                sh 'docker compose -f $COMPOSE_FILE up -d'
            }
        }

        stage('Health Check') {
            steps {
                sh 'sleep 10'
                sh 'curl -f http://localhost:8000/ || exit 1'
            }
        }
    }
}